-- MySQL Script generated by MySQL Workbench
-- Wed Sep 10 02:31:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema encuestas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema encuestas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `encuestas` DEFAULT CHARACTER SET utf8 ;
USE `encuestas` ;

-- -----------------------------------------------------
-- Table `encuestas`.`estado_encuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`estado_encuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`encuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`encuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `subtitulo` TEXT NULL,
  `descripcion` TEXT NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `estado_encuestas_id` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_eliminado` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_encuestas_estado_encuestas_idx` (`estado_encuestas_id` ASC) VISIBLE,
  CONSTRAINT `fk_encuestas_estado_encuestas`
    FOREIGN KEY (`estado_encuestas_id`)
    REFERENCES `encuestas`.`estado_encuestas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `encuestas_id` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_eliminado` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_encuestas1_idx` (`encuestas_id` ASC) VISIBLE,
  CONSTRAINT `fk_preguntas_encuestas`
    FOREIGN KEY (`encuestas_id`)
    REFERENCES `encuestas`.`encuestas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`preguntas_opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`preguntas_opciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `preguntas_id` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_eliminado` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_opciones_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_preguntas_opciones_preguntas`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `encuestas`.`preguntas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NULL,
  `preguntas_id` INT NOT NULL,
  `preguntas_opciones_id` INT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  INDEX `fk_respuestas_preguntas_opciones1_idx` (`preguntas_opciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_preguntas`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `encuestas`.`preguntas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_preguntas_opciones`
    FOREIGN KEY (`preguntas_opciones_id`)
    REFERENCES `encuestas`.`preguntas_opciones` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
